### ISSUE TITLE
Stripe Restricted API Key    

### ISSUE THREAD

**Issue by PankajSharma78** [odomojuli/regextokens#17]
Stripe Restricted API Key regex is incorrect, it should be :
regex : "rk_live_[0-9a-zA-Z]{24}"

**Comment by odomojuli** [comment]
Thank you for bringing this to my attention.

The documentation for Stripe's [API Keys](https://docs.stripe.com/keys) lists this as the example:
```
A string that starts with rk_test_
```

Test samples show a pattern with prefix:
```
rk_live_[0-9a-zA-Z]{99}
```

There is a static prefix alphanumeric word of length 17, followed by a consecutive alphanumeric word of length 82.
I'm not sure how this is sub-word may be applied consistently across restricted API keys.
This is still captured by the suggested pattern.

Other repositories list the alphanumeric word as being length 24.

Without any official citation, I will defer to my own measured samples being the case for length 99.

This issue is now closed.
